/*
 * keys.c
 *
 * Created on: Dec 2, 2025
 * Author: mertk
 */
/**
 * @file    keys.c
 * @brief   Storage for Cryptographic Keys.
 * @details Contains the AES-128 Secret Key for Firmware Encryption and
 * the ECDSA Public Key for Firmware Signature Verification.
 *
 * @note    These keys MUST match the keys used by the Python signing scripts.
 */

#include "keys.h"

// ============================================================================
// 1. AES-128 SECRET KEY
// ============================================================================
/**
 * @brief  AES-128 Secret Key (16 Bytes).
 * @note   Used for AES-CBC (Update Decryption) and AES-ECB (Backup Encryption).
 * Generated by keygen.py.
 */
const uint8_t AES_SECRET_KEY[16] = {
    0x65, 0x52, 0x17, 0x82,
	0xF1, 0x83, 0x26, 0xD5,
	0x28, 0xC5, 0x33, 0x2F,
	0xA1, 0x39, 0x42, 0x58
};

// ============================================================================
// 2. ECDSA PUBLIC KEY (SECP256R1)
// ============================================================================
/**
 * @brief  ECDSA Public Key (64 Bytes).
 * @note   Concatenation of Point X (32 bytes) and Point Y (32 bytes).
 * Used by uECC_verify() to validate the firmware signature.
 */
const uint8_t ECDSA_public_key_xy[64] = {
    /* X Coordinate */
		0xE6, 0x55, 0xD2, 0xC8, 0x9A, 0x85, 0x3D, 0xD2,
		0xD7, 0x16, 0x8E, 0xE0, 0x7E, 0x1E, 0x33, 0xEA,
		0xF9, 0xAD, 0x19, 0x96, 0xE0, 0x69, 0x73, 0xA3,
		0xA7, 0xFD, 0xEC, 0x14, 0x3C, 0xCD, 0xBB, 0x5B,

    /* Y Coordinate */
		 0x37, 0x86, 0x09, 0x4F, 0x22, 0x0A, 0x6B, 0x74,
		 0xD7, 0x0A, 0xC1, 0x44, 0x20, 0xFD, 0xD9, 0x42,
		 0x34, 0xF8, 0xB8, 0x6D, 0x07, 0xD6, 0x6B, 0xA3,
		 0x96, 0x55, 0x14, 0x73, 0xEB, 0x26, 0xB3, 0xCB
};
