/*
 * keys.c
 *
 * Created on: Dec 2, 2025
 * Author: mertk
 */
/**
 * @file    keys.c
 * @brief   Storage for Cryptographic Keys.
 * @details Contains the AES-128 Secret Key for Firmware Encryption and
 * the ECDSA Public Key for Firmware Signature Verification.
 *
 * @note    These keys MUST match the keys used by the Python signing scripts.
 */

#include "keys.h"

// ============================================================================
// 1. AES-128 SECRET KEY
// ============================================================================
/**
 * @brief  AES-128 Secret Key (16 Bytes).
 * @note   Used for AES-CBC (Update Decryption) and AES-ECB (Backup Encryption).
 * Generated by keygen.py.
 */
const uint8_t AES_SECRET_KEY[16] = {
    0x54, 0x1d, 0xaf, 0xcb, 0x78, 0x80, 0x03, 0x8b,
    0xc5, 0x31, 0xbe, 0x98, 0x97, 0xaa, 0x46, 0x95
};

// ============================================================================
// 2. ECDSA PUBLIC KEY (SECP256R1)
// ============================================================================
/**
 * @brief  ECDSA Public Key (64 Bytes).
 * @note   Concatenation of Point X (32 bytes) and Point Y (32 bytes).
 * Used by uECC_verify() to validate the firmware signature.
 */
const uint8_t ECDSA_public_key_xy[64] = {
    /* X Coordinate */
    0x28, 0xAC, 0x76, 0x9F, 0xB3, 0x89, 0x0D, 0x17,
    0x5B, 0xF8, 0x10, 0x4D, 0x83, 0x0D, 0xDD, 0x59,
    0xE6, 0x16, 0x7E, 0x58, 0x2D, 0x28, 0x37, 0x43,
    0x44, 0xB5, 0x8B, 0x80, 0x98, 0x29, 0xBA, 0x5F,

    /* Y Coordinate */
    0x99, 0xED, 0xDA, 0x3E, 0xB9, 0x83, 0x59, 0x36,
    0x7E, 0x76, 0x39, 0x46, 0x8B, 0x6F, 0x1F, 0x1F,
    0xDF, 0xD8, 0xB3, 0xB5, 0x32, 0x5E, 0x4A, 0xDB,
    0x5D, 0xFC, 0x8B, 0x64, 0x70, 0xC9, 0xA6, 0x95
};
