/*
 * keys.c
 *
 * Created on: Dec 2, 2025
 * Author: mertk
 */
/**
 * @file    keys.c
 * @brief   Storage for Cryptographic Keys.
 * @details Contains the AES-128 Secret Key for Firmware Encryption and
 * the ECDSA Public Key for Firmware Signature Verification.
 *
 * @note    These keys MUST match the keys used by the Python signing scripts.
 */

#include "keys.h"

// ============================================================================
// 1. AES-128 SECRET KEY
// ============================================================================
/**
 * @brief  AES-128 Secret Key (16 Bytes).
 * @note   Used for AES-CBC (Update Decryption) and AES-ECB (Backup Encryption).
 * Generated by keygen.py.
 */
const uint8_t AES_SECRET_KEY[16] = {
		0x7A, 0x6B, 0x88, 0xEB, 0x97, 0xC6, 0x05, 0x78,
		0xF8, 0x24, 0x73, 0xA0, 0x66, 0xBA, 0x5F, 0x5B
};

// ============================================================================
// 2. ECDSA PUBLIC KEY (SECP256R1)
// ============================================================================
/**
 * @brief  ECDSA Public Key (64 Bytes).
 * @note   Concatenation of Point X (32 bytes) and Point Y (32 bytes).
 * Used by uECC_verify() to validate the firmware signature.
 */
const uint8_t ECDSA_public_key_xy[64] = {
    /* X Coordinate */
	0x3C, 0xDE, 0x3A, 0xD2, 0x7E, 0xC2, 0xFB, 0xB7,
	0xFA, 0x3F, 0xE2, 0x09, 0xFB, 0xF3, 0xC7, 0x5F,
	0xEC, 0xC1, 0xE6, 0x7E, 0x71, 0xCD, 0x19, 0xD2,
	0x80, 0xE7, 0xAB, 0xBC, 0x6B, 0x8A, 0xB9, 0x7E,

    /* Y Coordinate */
	0x89, 0xB5, 0x35, 0x9B, 0xE8, 0x7B, 0x99, 0x7B,
	0x84, 0xDB, 0xEC, 0xD8, 0x7B, 0x28, 0x00, 0x5D,
	0xA8, 0xE6, 0x29, 0x5C, 0xDE, 0x3C, 0x7C, 0x34,
	0xC2, 0xE2, 0xBE, 0xD9, 0x17, 0x38, 0xFF, 0xA5
};
